;;; agent-ide-enlearn-test.el --- Tests for enlearn -*- lexical-binding: t; -*-

(require 'ert)

;; Stub deps if required by agent-ide-enlearn → agent-ide-session chain:
(unless (featurep 'acp)
  (provide 'acp))
(unless (featurep 'valign)
  (provide 'valign)
  (defun valign-mode (&rest _))
  (defun valign--guess-table-type (&rest _)))

(require 'agent-ide-enlearn)
(require 'agent-ide-submit-test)

(ert-deftest agent-ide-enlearn-detects-chinese ()
  (should (eq (agent-ide-enlearn--mode-for-text "帮我修这个 bug") 'translate))
  (should (eq (agent-ide-enlearn--mode-for-text "Please fix this bug") 'polish)))

(ert-deftest agent-ide-enlearn-parses-markdown-sections ()
  (let* ((raw "## Final\nFix the nil check in foo.el\n\n## Breakdown\n- 祈使句\n\n## Grammar\n- nil check 搭配\n")
         (parsed (agent-ide-enlearn--parse-response raw)))
    (should (equal (plist-get parsed :final) "Fix the nil check in foo.el"))
    (should (string-match-p "祈使句" (plist-get parsed :breakdown)))
    (should (string-match-p "nil check" (plist-get parsed :grammar)))
    (should (equal (plist-get parsed :raw) raw))))

(ert-deftest agent-ide-enlearn-tolerates-heading-trailing-whitespace ()
  (should (equal (agent-ide-enlearn--section "## Final  \nFix" "Final") "Fix"))
  (should (equal (agent-ide-enlearn--section "## Final\t\nFix" "Final") "Fix")))

(ert-deftest agent-ide-enlearn-empty-final-returns-nil ()
  (let ((parsed (agent-ide-enlearn--parse-response "## Final\n\n## Breakdown\n- foo")))
    (should (null (plist-get parsed :final)))
    (should (string-match-p "foo" (plist-get parsed :breakdown)))))

(ert-deftest agent-ide-enlearn-whitespace-only-final-returns-nil ()
  (let ((parsed (agent-ide-enlearn--parse-response "## Final\n   \n## Breakdown\n- foo")))
    (should (null (plist-get parsed :final)))))

(ert-deftest agent-ide-enlearn-parse-failure-returns-nil-final ()
  (let ((parsed (agent-ide-enlearn--parse-response "sorry I cannot")))
    (should (null (plist-get parsed :final)))
    (should (equal (plist-get parsed :breakdown) ""))
    (should (equal (plist-get parsed :grammar) ""))))

(ert-deftest agent-ide-enlearn-hook-defers-when-enabled ()
  (with-temp-buffer
    (agent-ide-session-mode)
    (let* ((session (agent-ide-submit-test--session))
           (sent 'unset)
           (agent-ide-enlearn-auto-send nil))
      (setq-local agent-ide--session session)
      (agent-ide-renderer-initialize-buffer session)
      (agent-ide-renderer-create-prompt session)
      (goto-char (marker-position (agent-ide-session-input-start-marker session)))
      (insert "帮我写测试")
      (agent-ide-enlearn-mode 1)
      (cl-letf (((symbol-function 'agent-ide-protocol-send-prompt)
                 (lambda (_s p) (setq sent p)))
                ((symbol-function 'agent-ide-enlearn--request)
                 (lambda (&rest _) nil)))
        (agent-ide-submit)
        (should (eq sent 'unset))
        (should (string-match-p "帮我写测试" (buffer-string)))
        (should (equal (agent-ide-session-status session) "coaching")))
      (agent-ide-enlearn-mode -1))))

(ert-deftest agent-ide-enlearn-send-delivers-final-only ()
  (with-temp-buffer
    (agent-ide-session-mode)
    (let* ((session (agent-ide-submit-test--session))
           (sent 'unset)
           (agent-ide-enlearn-auto-send nil)
           (fake-raw "## Final\nPlease write tests\n\n## Breakdown\n- x\n\n## Grammar\n- y\n"))
      (unwind-protect
          (progn
            (setq-local agent-ide--session session)
            (agent-ide-renderer-initialize-buffer session)
            (agent-ide-renderer-create-prompt session)
            (goto-char (marker-position (agent-ide-session-input-start-marker session)))
            (insert "帮我写测试")
            (agent-ide-enlearn-mode 1)
            (cl-letf (((symbol-function 'agent-ide-protocol-send-prompt)
                       (lambda (_s p) (setq sent p)))
                      ((symbol-function 'agent-ide-enlearn--request)
                       (lambda (session _mode _text)
                         (let ((request-id (plist-get (agent-ide-enlearn--pending-for session)
                                                      :request-id)))
                           (agent-ide-enlearn--handle-response session fake-raw request-id)))
              (agent-ide-submit)
              (should (eq sent 'unset))
              (agent-ide-enlearn-send)
              (should (equal sent "Please write tests"))))
        (agent-ide-enlearn-mode -1)))))))

(ert-deftest agent-ide-enlearn-auto-send-delivers ()
  (with-temp-buffer
    (agent-ide-session-mode)
    (let* ((session (agent-ide-submit-test--session))
           (sent 'unset)
           (agent-ide-enlearn-auto-send t)
           (fake-raw "## Final\nPlease write tests\n\n## Breakdown\n- x\n\n## Grammar\n- y\n"))
      (unwind-protect
          (progn
            (setq-local agent-ide--session session)
            (agent-ide-renderer-initialize-buffer session)
            (agent-ide-renderer-create-prompt session)
            (goto-char (marker-position (agent-ide-session-input-start-marker session)))
            (insert "帮我写测试")
            (agent-ide-enlearn-mode 1)
            (cl-letf (((symbol-function 'agent-ide-protocol-send-prompt)
                       (lambda (_s p) (setq sent p)))
                      ((symbol-function 'agent-ide-enlearn--request)
                       (lambda (session _mode _text)
                         (let ((request-id (plist-get (agent-ide-enlearn--pending-for session)
                                                      :request-id)))
                           (agent-ide-enlearn--handle-response session fake-raw request-id)))
              (agent-ide-submit)
              (should (equal sent "Please write tests"))))
        (agent-ide-enlearn-mode -1)))))))

(ert-deftest agent-ide-enlearn-cancel-does-not-send ()
  (with-temp-buffer
    (agent-ide-session-mode)
    (let* ((session (agent-ide-submit-test--session))
           (sent 'unset)
           (agent-ide-enlearn-auto-send nil)
           (fake-raw "## Final\nPlease write tests\n\n## Breakdown\n- x\n\n## Grammar\n- y\n"))
      (unwind-protect
          (progn
            (setq-local agent-ide--session session)
            (agent-ide-renderer-initialize-buffer session)
            (agent-ide-renderer-create-prompt session)
            (goto-char (marker-position (agent-ide-session-input-start-marker session)))
            (insert "帮我写测试")
            (agent-ide-enlearn-mode 1)
            (cl-letf (((symbol-function 'agent-ide-protocol-send-prompt)
                       (lambda (_s p) (setq sent p)))
                      ((symbol-function 'agent-ide-enlearn--request)
                       (lambda (session _mode _text)
                         (let ((request-id (plist-get (agent-ide-enlearn--pending-for session)
                                                      :request-id)))
                           (agent-ide-enlearn--handle-response session fake-raw request-id)))
              (agent-ide-submit)
              (agent-ide-enlearn-cancel)
              (should (eq sent 'unset))))
        (agent-ide-enlearn-mode -1)))))))

(ert-deftest agent-ide-enlearn-stale-callback-ignored-after-cancel ()
  (with-temp-buffer
    (agent-ide-session-mode)
    (let* ((session (agent-ide-submit-test--session))
           (sent 'unset)
           (late-callback nil)
           (agent-ide-enlearn-auto-send nil)
           (fake-raw "## Final\nPlease write tests\n\n## Breakdown\n- x\n\n## Grammar\n- y\n"))
      (unwind-protect
          (progn
            (setq-local agent-ide--session session)
            (agent-ide-renderer-initialize-buffer session)
            (agent-ide-renderer-create-prompt session)
            (goto-char (marker-position (agent-ide-session-input-start-marker session)))
            (insert "帮我写测试")
            (agent-ide-enlearn-mode 1)
            (cl-letf (((symbol-function 'agent-ide-protocol-send-prompt)
                       (lambda (_s p) (setq sent p)))
                      ((symbol-function 'agent-ide-enlearn--request)
                       (lambda (session _mode _text)
                         (let ((request-id (plist-get (agent-ide-enlearn--pending-for session)
                                                      :request-id)))
                           (setq late-callback
                                 (lambda ()
                                   (agent-ide-enlearn--handle-response
                                    session fake-raw request-id)))))
              (agent-ide-submit)
              (should (functionp late-callback))
              (agent-ide-enlearn-cancel)
              (funcall late-callback)
              (should (eq sent 'unset))
              (should (not (string-match-p "✦ English Coach" (buffer-string))))))
        (agent-ide-enlearn-mode -1)))))))

(ert-deftest agent-ide-enlearn-submit-sends-final-with-empty-input ()
  (with-temp-buffer
    (agent-ide-session-mode)
    (let* ((session (agent-ide-submit-test--session))
           (sent 'unset)
           (agent-ide-enlearn-auto-send nil)
           (fake-raw "## Final\nPlease write tests\n\n## Breakdown\n- x\n\n## Grammar\n- y\n"))
      (unwind-protect
          (progn
            (setq-local agent-ide--session session)
            (agent-ide-renderer-initialize-buffer session)
            (agent-ide-renderer-create-prompt session)
            (goto-char (marker-position (agent-ide-session-input-start-marker session)))
            (insert "帮我写测试")
            (agent-ide-enlearn-mode 1)
            (cl-letf (((symbol-function 'agent-ide-protocol-send-prompt)
                       (lambda (_s p) (setq sent p)))
                      ((symbol-function 'agent-ide-enlearn--request)
                       (lambda (session _mode _text)
                         (let ((request-id (plist-get (agent-ide-enlearn--pending-for session)
                                                      :request-id)))
                           (agent-ide-enlearn--handle-response session fake-raw request-id)))
              (agent-ide-submit)
              (should (eq sent 'unset))
              (agent-ide-renderer-replace-current-input session "")
              (agent-ide-submit)
              (should (equal sent "Please write tests"))))
        (agent-ide-enlearn-mode -1)))))))

(ert-deftest agent-ide-enlearn-skip-next-bypasses ()
  (with-temp-buffer
    (agent-ide-session-mode)
    (let* ((session (agent-ide-submit-test--session))
           (sent nil)
           (requested nil))
      (unwind-protect
          (progn
            (setq-local agent-ide--session session)
            (agent-ide-renderer-initialize-buffer session)
            (agent-ide-renderer-create-prompt session)
            (goto-char (marker-position (agent-ide-session-input-start-marker session)))
            (insert "plain english please")
            (agent-ide-enlearn-mode 1)
            (setq agent-ide-enlearn--skip-next t)
            (cl-letf (((symbol-function 'agent-ide-protocol-send-prompt)
                       (lambda (_s p) (setq sent p)))
                      ((symbol-function 'agent-ide-enlearn--request)
                       (lambda (&rest _) (setq requested t))))
              (agent-ide-submit)
              (should (equal sent "plain english please"))
              (should (null requested)))
        (agent-ide-enlearn-mode -1))))))

(ert-deftest agent-ide-enlearn-backend-error-abort-shows-actions ()
  (with-temp-buffer
    (agent-ide-session-mode)
    (let* ((session (agent-ide-submit-test--session))
           (agent-ide-enlearn-on-backend-error 'abort))
      (unwind-protect
          (progn
            (setq-local agent-ide--session session)
            (agent-ide-renderer-initialize-buffer session)
            (agent-ide-renderer-create-prompt session)
            (goto-char (marker-position (agent-ide-session-input-start-marker session)))
            (insert "帮我写测试")
            (agent-ide-enlearn-mode 1)
            (cl-letf (((symbol-function 'agent-ide-protocol-send-prompt)
                       (lambda (&rest _) (error "should not send")))
                      ((symbol-function 'agent-ide-enlearn--request)
                       (lambda (session &rest _)
                         (agent-ide-enlearn--render-error session "boom"))))
              (agent-ide-submit)
              (should (string-match-p "Retry" (buffer-string)))
              (should (string-match-p "Send original" (buffer-string)))
              (should (string-match-p "Cancel" (buffer-string))))
        (agent-ide-enlearn-mode -1))))))

(ert-deftest agent-ide-enlearn-send-original-on-error-config ()
  (with-temp-buffer
    (agent-ide-session-mode)
    (let* ((session (agent-ide-submit-test--session))
           (sent nil)
           (agent-ide-enlearn-on-backend-error 'send-original))
      (unwind-protect
          (progn
            (setq-local agent-ide--session session)
            (agent-ide-renderer-initialize-buffer session)
            (agent-ide-renderer-create-prompt session)
            (goto-char (marker-position (agent-ide-session-input-start-marker session)))
            (insert "帮我写测试")
            (agent-ide-enlearn-mode 1)
            (cl-letf (((symbol-function 'agent-ide-protocol-send-prompt)
                       (lambda (_s p) (setq sent p)))
                      ((symbol-function 'agent-ide-enlearn--request)
                       (lambda (session &rest _)
                         (agent-ide-enlearn--backend-unavailable session))))
              (agent-ide-submit)
              (should (equal sent "帮我写测试")))
        (agent-ide-enlearn-mode -1))))))

(ert-deftest agent-ide-enlearn-interrupt-cancels-coaching ()
  (with-temp-buffer
    (agent-ide-session-mode)
    (let* ((session (agent-ide-submit-test--session))
           (protocol-cancel-called nil)
           (agent-ide-enlearn-auto-send nil))
      (unwind-protect
          (progn
            (setq-local agent-ide--session session)
            (agent-ide-renderer-initialize-buffer session)
            (agent-ide-renderer-create-prompt session)
            (goto-char (marker-position (agent-ide-session-input-start-marker session)))
            (insert "帮我写测试")
            (agent-ide-enlearn-mode 1)
            (cl-letf (((symbol-function 'agent-ide-protocol-cancel)
                       (lambda (&rest _args) (setq protocol-cancel-called t)))
                      ((symbol-function 'agent-ide-enlearn--request)
                       (lambda (&rest _) nil)))
              (agent-ide-submit)
              (should (equal (agent-ide-session-status session) "coaching"))
              (should (agent-ide-enlearn--pending-for session))
              (agent-ide-interrupt)
              (should (not protocol-cancel-called))
              (should (null (agent-ide-enlearn--pending-for session)))
              (should (equal (agent-ide-session-status session) "idle")))
        (agent-ide-enlearn-mode -1))))))

(provide 'agent-ide-enlearn-test)
